default: true
MD003:
  style: atx
MD004: false
MD007:
  indent: 4
MD013: false
MD024:
  siblings_only: true
  allow_different_nesting: true
MD026:
  punctuation: .,;:!
MD033:
  allowed_elements:
    [br, small, table, thead, tbody, th, td, tr, col, colgroup, i]
